Updated README with example usage of new cost computing fn
ccurme/yolopandas pull request #32
Opened 2023-05-09 03:16 UTC by mturk24

Can see what README changes look like here: https://github.com/mturk24/yolopandas/tree/add-token-estimation-per-query

2023-05-10 22:43 UTC, ccurme requested changes
Thanks for this. Can you update the import statement?

btw, `utils.query_helpers` was released in yolopandas==0.0.6.

2023-05-10 22:43 UTC, ccurme commented on README.md
> +from utils.query_helpers import run_query_with_cost
Shouldn't this be
```suggestion
from yolopandas.utils.query_helpers import run_query_with_cost
```

2023-05-10 22:43 UTC, ccurme commented on README.md
> +Also, if you want to get a better idea of how much each query costs, you can use the function `run_query_with_cost` found in the utils package to compute the cost in $USD broken down by prompt/comple
nitpick:
```suggestion
Also, if you want to get a better idea of how much each query costs, you can use the function `run_query_with_cost` found in the utils module to compute the cost in $USD broken down by prompt/completion tokens:
```

2023-05-10 23:02 UTC, mturk24 commented
> Thanks for this. Can you update the import statement?
> 
> btw, `utils.query_helpers` was released in yolopandas==0.0.6.

Just fixed with new commits thank you! And awesome :)

2023-05-11 13:08 UTC, ccurme approved these changes

2023-05-11 13:08 UTC, merged